version: '2'
services:
  postgres:
    image: postgres
    container_name: "postgres"
    volumes:
     - data-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: pgdb
  db:
    image: mongo:3.0
    container_name: "mongo"
    volumes:
     - data-volume:/data/db
    command: "--smallfiles"
    environment:
     - MONGO_DATA_DIR=/data/db

networks:
  new:

volumes:
  data-volume:
