version: '2'
services:
  nexus:
    image: sonatype/nexus3
    container_name: "nexus"
    hostname: nexus
    networks:
      - new
    volumes:
     - data-volume:/nexus-data
  minio:
    image: minio/minio
    container_name: "minio"
    hostname: minio
    networks:
      - new
    volumes:
     - data-volume:/data
    environment:
     - MINIO_ACCESS_KEY=somelonginitialkey
     - MINIO_SECRET_KEY=somelongsecretkey
    command: server /data

volumes:
  data-volume:

networks:
  new:

# networks:
#     default:
#         external:
#             name: weave
